name: DevTest-Apply

on:
 # workflow_dispatch:
   push:
     branches:
      - main
     paths:
      - 'DevTest/**'

permissions:
    id-token: write   
    contents: read
      
defaults:
  run:
    working-directory: ./DevTest

      
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
        
        
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::094175769936:role/github-assume-role
          role-session-name: samplerolesession
          aws-region: us-east-1
      

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.4
          terraform_wrapper: false
      
      - name: Setup paths
        uses: dorny/paths-filter@v2
        id: filter
        with:
         filters: |
          path1:
            - 'DevTest/vic/**'
          path2:
            - 'DevTest/eks/**'

        # run only if 'path1' files were changed
      - name: path1 tests
        if: steps.filter.outputs.path1 == 'true' 
        run: |
          cd vic
      
          
      - name: path2 tests
        if: steps.filter.outputs.path2 == 'true'
        run: cd ./DevTest/eks
      
        
      
        

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        
      - name: Terraform Apply
        run: terraform apply -auto-approve
