name: DevTest-Apply

on:
  workflow_dispatch:
 # push:
 #   branches:
 #    - main
 #   paths:
 #    - 'DevTest/**'

permissions:
    id-token: write   
    contents: read
      

      
jobs:
  terraform-vic:
    name: "Terraform-vic"
    runs-on: ubuntu-latest 
    defaults:
     run:
      working-directory: ./DevTest/vic    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
           
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::094175769936:role/github-assume-role
          role-session-name: samplerolesession
          aws-region: us-east-1
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.4
          terraform_wrapper: false
       

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        
      - name: Terraform Apply
        run: terraform apply -auto-approve


  terraform-eks:
    name: "Terraform-eks"
    runs-on: ubuntu-latest 
    defaults:
     run:
      working-directory: ./DevTest/eks   
    steps:
      - name: Checkout
        uses: actions/checkout@v3
           
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::094175769936:role/github-assume-role
          role-session-name: samplerolesession
          aws-region: us-east-1
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.4
          terraform_wrapper: false
       

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        
      - name: Terraform Apply
        run: terraform apply -auto-approve

