name: DevTest-Plan

on:
  workflow_dispatch:
  # push:
  #  branches:
  #   - 'Feature-**'
  #  paths:
  #   - 'DevTest/**'

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: ./DevTest

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout private repo
        uses: actions/checkout@v2
        with:
          repository: org/private-repo
          ref: main # or specify the desired branch or commit
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::094175769936:role/github-assume-role
          role-session-name: samplerolesession
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.4
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
